DROP TRIGGER IF EXISTS FESTIVAL_RUNTIME_TRIGGER;

DROP TRIGGER IF EXISTS YEAR_TRIGGER;

DROP TRIGGER IF EXISTS FESTIVAL_DELETE_TRIGGER;

DROP TRIGGER IF EXISTS VENUE_UPDATE_TRIGGER;

DROP PROCEDURE IF EXISTS ADD_FILM;

DROP PROCEDURE IF EXISTS ADD_FESTIVAL;