-- Delete tables that currently exist in correct order

DROP TABLE IF EXISTS Scheduled_Film CASCADE;

DROP TABLE IF EXISTS Award_Winner CASCADE;

DROP TABLE IF EXISTS Film CASCADE;

DROP TABLE IF EXISTS Award CASCADE;

DROP TABLE IF EXISTS People CASCADE;

DROP TABLE IF EXISTS Venue CASCADE;

DROP TABLE IF EXISTS Festival CASCADE;